# initialization
monitor = DP-3, 3440x1440@180.00hz, 0x0, 1

## autostart programs

## env variables

## app preference
$terminal = alacritty

# main configuration
general {
	border_size = 2
	gaps_out = 30

	resize_on_border = true
}

## binds
$mainMod = SUPER

### open applications
bind = $mainMod, T, exec, $terminal
bind = $mainMod, R, exec, fuzzel

### window management

